In [0]:
import numpy as np

In [2]:
5 / 2

2.5

In [0]:
arr1 = np.array([[1, 2, 3, 4], [8, 9,10, 11]])

In [9]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

array同士の四則演算は同じ要素同士で行われる

In [10]:
arr1 + arr1 # 足し算

array([[ 2,  4,  6,  8],
       [16, 18, 20, 22]])

In [6]:
arr1 - arr1 # 引き算

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [5]:
arr1 * arr1 # 掛け算

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [11]:
arr1 / arr1 # 割り算

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

スカラー値とarrayの四則演算はarrayの全要素と行われる

In [17]:
arr1 + 2 # 足し算

array([[ 3,  4,  5,  6],
       [10, 11, 12, 13]])

In [18]:
1 - arr1 # 引き算

array([[  0,  -1,  -2,  -3],
       [ -7,  -8,  -9, -10]])

In [19]:
arr1 - 1 # 引き算

array([[ 0,  1,  2,  3],
       [ 7,  8,  9, 10]])

In [16]:
arr1 * 2 # 掛け算

array([[ 2,  4,  6,  8],
       [16, 18, 20, 22]])

In [14]:
1 / arr1 # 割り算

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [15]:
arr1 / 2 # 割り算

array([[0.5, 1. , 1.5, 2. ],
       [4. , 4.5, 5. , 5.5]])

In [8]:
arr1 ** 3 # 階乗

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])