<a href="https://colab.research.google.com/github/kisk0419/Python_learning/blob/master/udemy_ch13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [0]:
np.save('my_array', arr) # binaryデータとして保存

In [0]:
arr = np.arange(10)

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [0]:
arr1 = np.load('my_array.npy') # arrayを読み込む

In [0]:
arr2 = np.arange(10)

In [12]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.savez('ziparrays.npz', x=arr1, y=arr2) # ZIP形式で保存

In [0]:
archive_array = np.load('ziparrays.npz') # ZIP形式で読み込む

In [16]:
archive_array

In [17]:
archive_array['x'] # 保存時につけた名称でデータにアクセス

array([0, 1, 2, 3, 4])

In [18]:
archive_array['y'] # 保存時につけた名称でデータにアクセス

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])

In [20]:
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [0]:
np.savetxt('my_test_text.txt', arr, delimiter=',') # テキスト形式で保存

In [22]:
!cat my_test_text.txt

1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00,7.000000000000000000e+00


In [0]:
arr = np.loadtxt('my_test_text.txt', delimiter=',') # テキスト形式で読み込む

In [24]:
arr

array([[1., 2., 3., 4.],
       [4., 5., 6., 7.]])