In [1]:
import numpy as np
my_list1 = [1, 2, 3, 4]
my_array1 = np.array(my_list1) # Pythonのlistからarrayを作成する
my_array1

array([1, 2, 3, 4])

In [0]:
my_list2 = [11, 22, 33, 44]
my_lists = [my_list1, my_list2]

In [3]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [0]:
my_array2 = np.array(my_lists) # Pythonの多次元listから多次元のarrayを作成する

In [5]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [6]:
my_array2.shape # arrayの次元数を取得する

(2, 4)

In [7]:
my_array2.dtype # arrayの要素の型を取得する。Pythonのlistとことなり、arrayの要素は同じ型で統一する必要がある

dtype('int64')

In [8]:
np.zeros(5) # 要素が0で初期化されたarrayを作成する

array([0., 0., 0., 0., 0.])

In [0]:
my_zeros = np.zeros(5)

In [11]:
my_zeros.dtype

dtype('float64')

In [13]:
np.ones((5, 5)) # 要素が1で初期化されたarrayを作成する。多次元の場合はtuppleで次元数を指定する。

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.empty((3, 4)) # 要素が空（未初期化）のarrayを作成する

array([[2.83749094e-316, 2.51973479e-322, 0.00000000e+000,
        0.00000000e+000],
       [9.33678148e-313, 1.16095484e-028, 7.52736939e+252,
        2.86750350e+161],
       [1.44506353e+214, 2.28176682e+243, 9.96124223e-143,
        1.04018525e-314]])

In [15]:
np.eye(5) # 単位行列を作成する

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.arange(5) # Pythonのrangeのようにarrayを作成する

array([0, 1, 2, 3, 4])

In [17]:
np.arange(5, 50, 2) # 第3引数でstepを指定することもできる

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])