In [0]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [0]:
arr1 = np.arange(9).reshape((3,3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1, arr1], axis=1) # 列方向にarr1を連結

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1, arr1], axis=0) # 行方向にarr1を連結

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
ser1 = Series([0,1,2], index=['T','U','V'])
ser2 = Series([3,4], index=['X','Y'])

In [7]:
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1, ser2]) # Seriesを行方向に連結する

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1, ser2, ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [12]:
pd.concat([ser1, ser2], axis=1, sort=False) # Seriesを列方向に連結。DataFrameになる。

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [13]:
pd.concat([ser1, ser2], keys=['cat1', 'cat2']) # keyを指定して行方向に連結するとindexが階層化する

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [15]:
pd.concat([ser1, ser2], keys=['cat1', 'cat2'], axis=1, sort=False)  # keyを指定して列方向に連結するとkeyがカラムになる

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [0]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])

In [18]:
dframe1

X         Y         Z
0 -1.076485 -0.508258  0.469766
1 -0.131542  0.154896 -1.024687
2 -0.276280 -0.822109 -2.402287
3 -0.455650 -0.063849 -1.062505

In [0]:
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])

In [20]:
dframe2

Y         Q         X
0  0.749436  1.333625 -0.469363
1 -0.636736 -0.138957 -0.271733
2 -0.369756  1.111970 -1.011429

In [22]:
pd.concat([dframe1, dframe2], sort=False) # DataFrameを行方向に連結

X         Y         Z         Q
0 -1.076485 -0.508258  0.469766       NaN
1 -0.131542  0.154896 -1.024687       NaN
2 -0.276280 -0.822109 -2.402287       NaN
3 -0.455650 -0.063849 -1.062505       NaN
0 -0.469363  0.749436       NaN  1.333625
1 -0.271733 -0.636736       NaN -0.138957
2 -1.011429 -0.369756       NaN  1.111970

In [24]:
pd.concat([dframe1, dframe2], ignore_index=True, sort=False) # indexを無視するとindexを振り直してくれる

X         Y         Z         Q
0 -1.076485 -0.508258  0.469766       NaN
1 -0.131542  0.154896 -1.024687       NaN
2 -0.276280 -0.822109 -2.402287       NaN
3 -0.455650 -0.063849 -1.062505       NaN
4 -0.469363  0.749436       NaN  1.333625
5 -0.271733 -0.636736       NaN -0.138957
6 -1.011429 -0.369756       NaN  1.111970