In [0]:
import numpy as np

In [0]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr) # 平方根

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr) # eを底とする指数関数

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [0]:
A = np.random.randn(10) # 正規分布に従う乱数

In [7]:
A

array([-1.39724225,  0.08175694, -0.4405556 , -0.42324244,  0.93959268,
       -2.03214188,  0.01189171, -0.27772877, -1.05027933, -0.4273949 ])

In [0]:
B = np.random.randn(10)

In [9]:
B

array([ 1.44622733, -0.59246923,  1.36212528, -0.9520888 , -1.09455668,
       -0.50350944, -0.5191521 ,  0.70480815,  0.86631583, -0.24777414])

In [10]:
np.add(A, B) # 各要素で足し算

array([ 0.04898508, -0.51071229,  0.92156968, -1.37533123, -0.154964  ,
       -2.53565132, -0.50726039,  0.42707938, -0.1839635 , -0.67516904])

In [11]:
A + B

array([ 0.04898508, -0.51071229,  0.92156968, -1.37533123, -0.154964  ,
       -2.53565132, -0.50726039,  0.42707938, -0.1839635 , -0.67516904])

In [12]:
np.maximum(A, B) # 各要素の大きいほうを取得

array([ 1.44622733,  0.08175694,  1.36212528, -0.42324244,  0.93959268,
       -0.50350944,  0.01189171,  0.70480815,  0.86631583, -0.24777414])