In [0]:
import numpy as np

In [0]:
arr = np.arange(9).reshape((3, 3))

In [6]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [8]:
arr * arr.T

array([[ 0,  3, 12],
       [ 3, 16, 35],
       [12, 35, 64]])

In [9]:
arr.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [13]:
arr.transpose((0, 1)) # 元の配列と同じ

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
arr.transpose((1, 0)) # 行と列を入れ替える

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [15]:
arr.swapaxes(0, 1)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [16]:
arr.swapaxes(1, 0)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [17]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.dot(arr.T, arr) # ベクトルの内積

array([[45, 54, 63],
       [54, 66, 78],
       [63, 78, 93]])

In [0]:
arr3d = np.arange(12).reshape((3, 2, 2))

In [20]:
arr3d

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [21]:
arr3d[0]

array([[0, 1],
       [2, 3]])

In [25]:
arr3d.transpose((2, 1, 0))

array([[[ 0,  4,  8],
        [ 2,  6, 10]],

       [[ 1,  5,  9],
        [ 3,  7, 11]]])

In [24]:
arr3d.T

array([[[ 0,  4,  8],
        [ 2,  6, 10]],

       [[ 1,  5,  9],
        [ 3,  7, 11]]])